/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Amenity = {
  _id: string;
  _type: "amenity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  value?: string;
  label?: string;
  icon?: string;
  order?: number;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkId?: string;
  name?: string;
  email?: string;
  phone?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  savedListings?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "property";
  }>;
  createdAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  property?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "property";
  };
  agent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "agent";
  };
  buyerName?: string;
  buyerEmail?: string;
  buyerPhone?: string;
  message?: string;
  status?: "new" | "contacted" | "closed";
  createdAt?: string;
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  propertyType?: "house" | "apartment" | "condo" | "townhouse" | "land";
  status?: "active" | "pending" | "sold";
  bedrooms?: number;
  bathrooms?: number;
  squareFeet?: number;
  yearBuilt?: number;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  };
  location?: Geopoint;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  amenities?: Array<string>;
  agent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "agent";
  };
  lotSize?: number;
  openHouseDate?: string;
  originalPrice?: number;
  featured?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type Agent = {
  _id: string;
  _type: "agent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  name?: string;
  email?: string;
  phone?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  licenseNumber?: string;
  agency?: string;
  onboardingComplete?: boolean;
  createdAt?: string;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes = Amenity | User | SanityImageCrop | SanityImageHotspot | Lead | Property | Agent | Geopoint | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: FEATURED_PROPERTIES_QUERY
// Query: *[_type == "property" && featured == true && status == "active"][0...6] {    _id,    title,    "slug": slug.current,    price,    bedrooms,    bathrooms,    squareFeet,    address,    "image": images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    location  }
export type FEATURED_PROPERTIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  squareFeet: number | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  location: Geopoint | null;
}>;
// Variable: PROPERTIES_SEARCH_QUERY
// Query: *[_type == "property" && status == "active"    && price >= $minPrice && price <= $maxPrice    && ($beds == 0 || ($bedsIsPlus == true && bedrooms >= $beds) || ($bedsIsPlus == false && bedrooms == $beds))    && ($baths == 0 || ($bathsIsPlus == true && bathrooms >= $baths) || ($bathsIsPlus == false && bathrooms == $baths))    && ($type == "" || propertyType == $type)    && ($city == "" || lower(address.city) match $city + "*" || lower(address.state) match $city + "*" || lower(address.zipCode) match $city + "*")    && ($minSqft == 0 || squareFeet >= $minSqft)    && ($maxSqft == 0 || squareFeet <= $maxSqft)    && ($minYear == 0 || yearBuilt >= $minYear)    && ($maxYear == 0 || yearBuilt <= $maxYear)    && ($minLotSize == 0 || lotSize >= $minLotSize)    && ($maxLotSize == 0 || lotSize <= $maxLotSize)    && ($daysOnMarket == 0 || dateTime(createdAt) >= dateTime(now()) - 60*60*24*$daysOnMarket)    && ($openHouse == false || (openHouseDate != null && dateTime(openHouseDate) >= dateTime(now())))    && ($priceReduced == false || (originalPrice != null && price < originalPrice))    && ($amenitiesCount == 0 || count((amenities)[@ in $amenities]) == $amenitiesCount)  ] | order(createdAt desc) [$start...$end] {    _id,    title,    "slug": slug.current,    price,    originalPrice,    bedrooms,    bathrooms,    squareFeet,    yearBuilt,    lotSize,    address,    "image": images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    location,    amenities,    openHouseDate,    createdAt  }
export type PROPERTIES_SEARCH_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  originalPrice: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  squareFeet: number | null;
  yearBuilt: number | null;
  lotSize: number | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  location: Geopoint | null;
  amenities: Array<string> | null;
  openHouseDate: string | null;
  createdAt: string | null;
}>;
// Variable: PROPERTIES_COUNT_QUERY
// Query: count(*[_type == "property" && status == "active"    && price >= $minPrice && price <= $maxPrice    && ($beds == 0 || ($bedsIsPlus == true && bedrooms >= $beds) || ($bedsIsPlus == false && bedrooms == $beds))    && ($baths == 0 || ($bathsIsPlus == true && bathrooms >= $baths) || ($bathsIsPlus == false && bathrooms == $baths))    && ($type == "" || propertyType == $type)    && ($city == "" || lower(address.city) match $city + "*" || lower(address.state) match $city + "*" || lower(address.zipCode) match $city + "*")    && ($minSqft == 0 || squareFeet >= $minSqft)    && ($maxSqft == 0 || squareFeet <= $maxSqft)    && ($minYear == 0 || yearBuilt >= $minYear)    && ($maxYear == 0 || yearBuilt <= $maxYear)    && ($minLotSize == 0 || lotSize >= $minLotSize)    && ($maxLotSize == 0 || lotSize <= $maxLotSize)    && ($daysOnMarket == 0 || dateTime(createdAt) >= dateTime(now()) - 60*60*24*$daysOnMarket)    && ($openHouse == false || (openHouseDate != null && dateTime(openHouseDate) >= dateTime(now())))    && ($priceReduced == false || (originalPrice != null && price < originalPrice))    && ($amenitiesCount == 0 || count((amenities)[@ in $amenities]) == $amenitiesCount)  ])
export type PROPERTIES_COUNT_QUERYResult = number;
// Variable: PROPERTY_DETAIL_QUERY
// Query: *[_type == "property" && _id == $id][0] {    _id,    title,    description,    price,    propertyType,    status,    bedrooms,    bathrooms,    squareFeet,    yearBuilt,    address,    location,    images[] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    amenities,    agent-> {      _id,      userId,      name,      email,      phone,      photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },      bio,      agency    }  }
export type PROPERTY_DETAIL_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  propertyType: "apartment" | "condo" | "house" | "land" | "townhouse" | null;
  status: "active" | "pending" | "sold" | null;
  bedrooms: number | null;
  bathrooms: number | null;
  squareFeet: number | null;
  yearBuilt: number | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  } | null;
  location: Geopoint | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  }> | null;
  amenities: Array<string> | null;
  agent: {
    _id: string;
    userId: string | null;
    name: string | null;
    email: string | null;
    phone: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: null;
    } | null;
    bio: string | null;
    agency: string | null;
  } | null;
} | null;
// Variable: AGENT_LISTINGS_QUERY
// Query: *[_type == "property" && agent._ref == $agentId] | order(createdAt desc) {    _id,    title,    "slug": slug.current,    price,    status,    bedrooms,    bathrooms,    "image": images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    createdAt  }
export type AGENT_LISTINGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  status: "active" | "pending" | "sold" | null;
  bedrooms: number | null;
  bathrooms: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  createdAt: string | null;
}>;
// Variable: AGENT_LEADS_QUERY
// Query: *[_type == "lead" && agent._ref == $agentId] | order(createdAt desc) {    _id,    buyerName,    buyerEmail,    buyerPhone,    status,    createdAt,    property-> {      _id,      title,      "slug": slug.current    }  }
export type AGENT_LEADS_QUERYResult = Array<{
  _id: string;
  buyerName: string | null;
  buyerEmail: string | null;
  buyerPhone: string | null;
  status: "closed" | "contacted" | "new" | null;
  createdAt: string | null;
  property: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
}>;
// Variable: USER_PROFILE_QUERY
// Query: *[_type == "user" && clerkId == $clerkId][0] {    _id,    name,    email,    phone,    photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    createdAt  }
export type USER_PROFILE_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: null;
  } | null;
  createdAt: string | null;
} | null;
// Variable: USER_EXISTS_QUERY
// Query: *[_type == "user" && clerkId == $clerkId][0]{ _id }
export type USER_EXISTS_QUERYResult = {
  _id: string;
} | null;
// Variable: AGENT_PROFILE_QUERY
// Query: *[_type == "agent" && userId == $userId][0] {    _id,    name,    email,    phone,    photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    bio,    licenseNumber,    agency,    onboardingComplete  }
export type AGENT_PROFILE_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: null;
  } | null;
  bio: string | null;
  licenseNumber: string | null;
  agency: string | null;
  onboardingComplete: boolean | null;
} | null;
// Variable: AGENT_BY_USER_ID_QUERY
// Query: *[_type == "agent" && userId == $userId][0] {    _id,    userId,    name,    email,    onboardingComplete  }
export type AGENT_BY_USER_ID_QUERYResult = {
  _id: string;
  userId: string | null;
  name: string | null;
  email: string | null;
  onboardingComplete: boolean | null;
} | null;
// Variable: LISTING_BY_ID_QUERY
// Query: *[_type == "property" && _id == $id][0] {    _id,    title,    description,    price,    propertyType,    status,    bedrooms,    bathrooms,    squareFeet,    yearBuilt,    address,    location,    images[] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    amenities,    agent  }
export type LISTING_BY_ID_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  propertyType: "apartment" | "condo" | "house" | "land" | "townhouse" | null;
  status: "active" | "pending" | "sold" | null;
  bedrooms: number | null;
  bathrooms: number | null;
  squareFeet: number | null;
  yearBuilt: number | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  } | null;
  location: Geopoint | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  }> | null;
  amenities: Array<string> | null;
  agent: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "agent";
  } | null;
} | null;
// Variable: USER_SAVED_LISTINGS_QUERY
// Query: *[_type == "user" && clerkId == $clerkId][0] {    savedListings[]-> {      _id,      title,      "slug": slug.current,      price,      bedrooms,      bathrooms,      squareFeet,      address,      "image": images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },      status    }  }.savedListings
export type USER_SAVED_LISTINGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  squareFeet: number | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  status: "active" | "pending" | "sold" | null;
}> | null;
// Variable: ANALYTICS_AGENT_QUERY
// Query: *[_type == "agent" && userId == $userId][0]{ _id, name, onboardingComplete }
export type ANALYTICS_AGENT_QUERYResult = {
  _id: string;
  name: string | null;
  onboardingComplete: boolean | null;
} | null;
// Variable: ANALYTICS_LISTINGS_TOTAL_QUERY
// Query: count(*[_type == "property" && agent._ref == $agentId])
export type ANALYTICS_LISTINGS_TOTAL_QUERYResult = number;
// Variable: ANALYTICS_LISTINGS_ACTIVE_QUERY
// Query: count(*[_type == "property" && agent._ref == $agentId && status == "active"])
export type ANALYTICS_LISTINGS_ACTIVE_QUERYResult = number;
// Variable: ANALYTICS_LISTINGS_PENDING_QUERY
// Query: count(*[_type == "property" && agent._ref == $agentId && status == "pending"])
export type ANALYTICS_LISTINGS_PENDING_QUERYResult = number;
// Variable: ANALYTICS_LISTINGS_SOLD_QUERY
// Query: count(*[_type == "property" && agent._ref == $agentId && status == "sold"])
export type ANALYTICS_LISTINGS_SOLD_QUERYResult = number;
// Variable: ANALYTICS_LEADS_TOTAL_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId])
export type ANALYTICS_LEADS_TOTAL_QUERYResult = number;
// Variable: ANALYTICS_LEADS_NEW_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId && status == "new"])
export type ANALYTICS_LEADS_NEW_QUERYResult = number;
// Variable: ANALYTICS_LEADS_CONTACTED_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId && status == "contacted"])
export type ANALYTICS_LEADS_CONTACTED_QUERYResult = number;
// Variable: ANALYTICS_LEADS_CLOSED_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId && status == "closed"])
export type ANALYTICS_LEADS_CLOSED_QUERYResult = number;
// Variable: ANALYTICS_LEADS_BY_PROPERTY_QUERY
// Query: *[_type == "property" && agent._ref == $agentId]{    "title": title,    "leadCount": count(*[_type == "lead" && property._ref == ^._id])  } | order(leadCount desc)[0...10]
export type ANALYTICS_LEADS_BY_PROPERTY_QUERYResult = Array<{
  title: string | null;
  leadCount: number;
}>;
// Variable: AMENITIES_QUERY
// Query: *[_type == "amenity"] | order(order asc, label asc) {    _id,    value,    label,    icon  }
export type AMENITIES_QUERYResult = Array<{
  _id: string;
  value: string | null;
  label: string | null;
  icon: string | null;
}>;
// Variable: AGENT_ID_BY_USER_QUERY
// Query: *[_type == "agent" && userId == $userId][0]{ _id }
export type AGENT_ID_BY_USER_QUERYResult = {
  _id: string;
} | null;
// Variable: AGENT_DASHBOARD_QUERY
// Query: *[_type == "agent" && userId == $userId][0]{ _id, name, onboardingComplete }
export type AGENT_DASHBOARD_QUERYResult = {
  _id: string;
  name: string | null;
  onboardingComplete: boolean | null;
} | null;
// Variable: AGENT_ONBOARDING_CHECK_QUERY
// Query: *[_type == "agent" && userId == $userId][0]{ _id, onboardingComplete }
export type AGENT_ONBOARDING_CHECK_QUERYResult = {
  _id: string;
  onboardingComplete: boolean | null;
} | null;
// Variable: USER_CONTACT_QUERY
// Query: *[_type == "user" && clerkId == $clerkId][0]{ name, email, phone }
export type USER_CONTACT_QUERYResult = {
  name: string | null;
  email: string | null;
  phone: string | null;
} | null;
// Variable: USER_SAVED_IDS_QUERY
// Query: *[_type == "user" && clerkId == $clerkId][0]{ _id, "savedIds": savedListings[]._ref }
export type USER_SAVED_IDS_QUERYResult = {
  _id: string;
  savedIds: Array<string> | null;
} | null;
// Variable: LEAD_EXISTS_QUERY
// Query: *[_type == "lead" && property._ref == $propertyId && buyerEmail == $email][0]{ _id }
export type LEAD_EXISTS_QUERYResult = {
  _id: string;
} | null;
// Variable: LEAD_AGENT_REF_QUERY
// Query: *[_type == "lead" && _id == $leadId][0]{ agent }
export type LEAD_AGENT_REF_QUERYResult = {
  agent: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "agent";
  } | null;
} | null;
// Variable: PROPERTY_AGENT_REF_QUERY
// Query: *[_type == "property" && _id == $id][0]{ agent }
export type PROPERTY_AGENT_REF_QUERYResult = {
  agent: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "agent";
  } | null;
} | null;
// Variable: DASHBOARD_LISTINGS_COUNT_QUERY
// Query: count(*[_type == "property" && agent._ref == $agentId])
export type DASHBOARD_LISTINGS_COUNT_QUERYResult = number;
// Variable: DASHBOARD_LEADS_COUNT_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId])
export type DASHBOARD_LEADS_COUNT_QUERYResult = number;
// Variable: DASHBOARD_NEW_LEADS_COUNT_QUERY
// Query: count(*[_type == "lead" && agent._ref == $agentId && status == "new"])
export type DASHBOARD_NEW_LEADS_COUNT_QUERYResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"property\" && featured == true && status == \"active\"][0...6] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    bedrooms,\n    bathrooms,\n    squareFeet,\n    address,\n    \"image\": images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    location\n  }\n": FEATURED_PROPERTIES_QUERYResult;
    "\n  *[_type == \"property\" && status == \"active\"\n    && price >= $minPrice && price <= $maxPrice\n    && ($beds == 0 || ($bedsIsPlus == true && bedrooms >= $beds) || ($bedsIsPlus == false && bedrooms == $beds))\n    && ($baths == 0 || ($bathsIsPlus == true && bathrooms >= $baths) || ($bathsIsPlus == false && bathrooms == $baths))\n    && ($type == \"\" || propertyType == $type)\n    && ($city == \"\" || lower(address.city) match $city + \"*\" || lower(address.state) match $city + \"*\" || lower(address.zipCode) match $city + \"*\")\n    && ($minSqft == 0 || squareFeet >= $minSqft)\n    && ($maxSqft == 0 || squareFeet <= $maxSqft)\n    && ($minYear == 0 || yearBuilt >= $minYear)\n    && ($maxYear == 0 || yearBuilt <= $maxYear)\n    && ($minLotSize == 0 || lotSize >= $minLotSize)\n    && ($maxLotSize == 0 || lotSize <= $maxLotSize)\n    && ($daysOnMarket == 0 || dateTime(createdAt) >= dateTime(now()) - 60*60*24*$daysOnMarket)\n    && ($openHouse == false || (openHouseDate != null && dateTime(openHouseDate) >= dateTime(now())))\n    && ($priceReduced == false || (originalPrice != null && price < originalPrice))\n    && ($amenitiesCount == 0 || count((amenities)[@ in $amenities]) == $amenitiesCount)\n  ] | order(createdAt desc) [$start...$end] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    originalPrice,\n    bedrooms,\n    bathrooms,\n    squareFeet,\n    yearBuilt,\n    lotSize,\n    address,\n    \"image\": images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    location,\n    amenities,\n    openHouseDate,\n    createdAt\n  }\n": PROPERTIES_SEARCH_QUERYResult;
    "\n  count(*[_type == \"property\" && status == \"active\"\n    && price >= $minPrice && price <= $maxPrice\n    && ($beds == 0 || ($bedsIsPlus == true && bedrooms >= $beds) || ($bedsIsPlus == false && bedrooms == $beds))\n    && ($baths == 0 || ($bathsIsPlus == true && bathrooms >= $baths) || ($bathsIsPlus == false && bathrooms == $baths))\n    && ($type == \"\" || propertyType == $type)\n    && ($city == \"\" || lower(address.city) match $city + \"*\" || lower(address.state) match $city + \"*\" || lower(address.zipCode) match $city + \"*\")\n    && ($minSqft == 0 || squareFeet >= $minSqft)\n    && ($maxSqft == 0 || squareFeet <= $maxSqft)\n    && ($minYear == 0 || yearBuilt >= $minYear)\n    && ($maxYear == 0 || yearBuilt <= $maxYear)\n    && ($minLotSize == 0 || lotSize >= $minLotSize)\n    && ($maxLotSize == 0 || lotSize <= $maxLotSize)\n    && ($daysOnMarket == 0 || dateTime(createdAt) >= dateTime(now()) - 60*60*24*$daysOnMarket)\n    && ($openHouse == false || (openHouseDate != null && dateTime(openHouseDate) >= dateTime(now())))\n    && ($priceReduced == false || (originalPrice != null && price < originalPrice))\n    && ($amenitiesCount == 0 || count((amenities)[@ in $amenities]) == $amenitiesCount)\n  ])\n": PROPERTIES_COUNT_QUERYResult;
    "\n  *[_type == \"property\" && _id == $id][0] {\n    _id,\n    title,\n    description,\n    price,\n    propertyType,\n    status,\n    bedrooms,\n    bathrooms,\n    squareFeet,\n    yearBuilt,\n    address,\n    location,\n    images[] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    amenities,\n    agent-> {\n      _id,\n      userId,\n      name,\n      email,\n      phone,\n      photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n      bio,\n      agency\n    }\n  }\n": PROPERTY_DETAIL_QUERYResult;
    "\n  *[_type == \"property\" && agent._ref == $agentId] | order(createdAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    price,\n    status,\n    bedrooms,\n    bathrooms,\n    \"image\": images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    createdAt\n  }\n": AGENT_LISTINGS_QUERYResult;
    "\n  *[_type == \"lead\" && agent._ref == $agentId] | order(createdAt desc) {\n    _id,\n    buyerName,\n    buyerEmail,\n    buyerPhone,\n    status,\n    createdAt,\n    property-> {\n      _id,\n      title,\n      \"slug\": slug.current\n    }\n  }\n": AGENT_LEADS_QUERYResult;
    "\n  *[_type == \"user\" && clerkId == $clerkId][0] {\n    _id,\n    name,\n    email,\n    phone,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    createdAt\n  }\n": USER_PROFILE_QUERYResult;
    "\n  *[_type == \"user\" && clerkId == $clerkId][0]{ _id }\n": USER_EXISTS_QUERYResult;
    "\n  *[_type == \"agent\" && userId == $userId][0] {\n    _id,\n    name,\n    email,\n    phone,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    bio,\n    licenseNumber,\n    agency,\n    onboardingComplete\n  }\n": AGENT_PROFILE_QUERYResult;
    "\n  *[_type == \"agent\" && userId == $userId][0] {\n    _id,\n    userId,\n    name,\n    email,\n    onboardingComplete\n  }\n": AGENT_BY_USER_ID_QUERYResult;
    "\n  *[_type == \"property\" && _id == $id][0] {\n    _id,\n    title,\n    description,\n    price,\n    propertyType,\n    status,\n    bedrooms,\n    bathrooms,\n    squareFeet,\n    yearBuilt,\n    address,\n    location,\n    images[] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    amenities,\n    agent\n  }\n": LISTING_BY_ID_QUERYResult;
    "\n  *[_type == \"user\" && clerkId == $clerkId][0] {\n    savedListings[]-> {\n      _id,\n      title,\n      \"slug\": slug.current,\n      price,\n      bedrooms,\n      bathrooms,\n      squareFeet,\n      address,\n      \"image\": images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n      status\n    }\n  }.savedListings\n": USER_SAVED_LISTINGS_QUERYResult;
    "\n  *[_type == \"agent\" && userId == $userId][0]{ _id, name, onboardingComplete }\n": ANALYTICS_AGENT_QUERYResult | AGENT_DASHBOARD_QUERYResult;
    "\n  count(*[_type == \"property\" && agent._ref == $agentId])\n": ANALYTICS_LISTINGS_TOTAL_QUERYResult | DASHBOARD_LISTINGS_COUNT_QUERYResult;
    "\n  count(*[_type == \"property\" && agent._ref == $agentId && status == \"active\"])\n": ANALYTICS_LISTINGS_ACTIVE_QUERYResult;
    "\n  count(*[_type == \"property\" && agent._ref == $agentId && status == \"pending\"])\n": ANALYTICS_LISTINGS_PENDING_QUERYResult;
    "\n  count(*[_type == \"property\" && agent._ref == $agentId && status == \"sold\"])\n": ANALYTICS_LISTINGS_SOLD_QUERYResult;
    "\n  count(*[_type == \"lead\" && agent._ref == $agentId])\n": ANALYTICS_LEADS_TOTAL_QUERYResult | DASHBOARD_LEADS_COUNT_QUERYResult;
    "\n  count(*[_type == \"lead\" && agent._ref == $agentId && status == \"new\"])\n": ANALYTICS_LEADS_NEW_QUERYResult | DASHBOARD_NEW_LEADS_COUNT_QUERYResult;
    "\n  count(*[_type == \"lead\" && agent._ref == $agentId && status == \"contacted\"])\n": ANALYTICS_LEADS_CONTACTED_QUERYResult;
    "\n  count(*[_type == \"lead\" && agent._ref == $agentId && status == \"closed\"])\n": ANALYTICS_LEADS_CLOSED_QUERYResult;
    "\n  *[_type == \"property\" && agent._ref == $agentId]{\n    \"title\": title,\n    \"leadCount\": count(*[_type == \"lead\" && property._ref == ^._id])\n  } | order(leadCount desc)[0...10]\n": ANALYTICS_LEADS_BY_PROPERTY_QUERYResult;
    "\n  *[_type == \"amenity\"] | order(order asc, label asc) {\n    _id,\n    value,\n    label,\n    icon\n  }\n": AMENITIES_QUERYResult;
    "\n  *[_type == \"agent\" && userId == $userId][0]{ _id }\n": AGENT_ID_BY_USER_QUERYResult;
    "\n  *[_type == \"agent\" && userId == $userId][0]{ _id, onboardingComplete }\n": AGENT_ONBOARDING_CHECK_QUERYResult;
    "\n  *[_type == \"user\" && clerkId == $clerkId][0]{ name, email, phone }\n": USER_CONTACT_QUERYResult;
    "\n  *[_type == \"user\" && clerkId == $clerkId][0]{ _id, \"savedIds\": savedListings[]._ref }\n": USER_SAVED_IDS_QUERYResult;
    "\n  *[_type == \"lead\" && property._ref == $propertyId && buyerEmail == $email][0]{ _id }\n": LEAD_EXISTS_QUERYResult;
    "\n  *[_type == \"lead\" && _id == $leadId][0]{ agent }\n": LEAD_AGENT_REF_QUERYResult;
    "\n  *[_type == \"property\" && _id == $id][0]{ agent }\n": PROPERTY_AGENT_REF_QUERYResult;
  }
}
